const center={latitude:36.8904302,longitude:-111.4496704};
const records=[],markers=new Map();let map,boundaryEditing=false,boundaryPoints=[],boundaryLayer=null;
const $=id=>document.getElementById(id);
function init(){map=L.map('collectorMap').setView([center.latitude,center.longitude],17);const sat=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:20,attribution:'Tiles © Esri'}).addTo(map);const street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'});L.control.layers({Satellite:sat,Streets:street}).addTo(map);bind()}
function bind(){
 $('photoInput').addEventListener('change',importPhotos); $('toggleBoundary').addEventListener('click',()=>{boundaryEditing=!boundaryEditing;$('toggleBoundary').textContent=boundaryEditing?'Stop boundary editing':'Start boundary editing';$('importStatus').textContent=boundaryEditing?'Boundary editing active: click points around the property in order.':`${records.length} photo record${records.length===1?'':'s'} loaded.`});
 $('undoBoundary').addEventListener('click',()=>{boundaryPoints.pop();drawBoundary()}); $('clearBoundary').addEventListener('click',()=>{boundaryPoints=[];drawBoundary()}); $('exportInventory').addEventListener('click',exportInventory);$('exportSite').addEventListener('click',exportSite);map.on('click',e=>{if(boundaryEditing){boundaryPoints.push({latitude:e.latlng.lat,longitude:e.latlng.lng});drawBoundary();}})
}
async function importPhotos(e){const files=[...e.target.files];if(!files.length)return;$('importStatus').textContent=`Reading metadata from ${files.length} file${files.length===1?'':'s'}…`;let gpsCount=0;
 for(const file of files){let exif={};try{exif=await exifr.parse(file,{gps:true,tiff:true,exif:true,ifd0:true})||{};}catch(err){console.warn(err)}const lat=exif.latitude,lon=exif.longitude;if(Number.isFinite(lat)&&Number.isFinite(lon))gpsCount++;const id=`LOC-${String(records.length+1).padStart(3,'0')}`;const url=URL.createObjectURL(file);const rec={id,filename:file.name,title:'',industry:'metal salvage',material:'Steel',form:'',attributes:[],description:'',tags:[],landmark:'',notes:'',cameraLocation:Number.isFinite(lat)&&Number.isFinite(lon)?{latitude:lat,longitude:lon}:null,materialLocation:Number.isFinite(lat)&&Number.isFinite(lon)?{latitude:lat,longitude:lon}:null,images:[`images/${file.name}`],previewUrl:url,capturedAt:formatDate(exif.DateTimeOriginal||exif.CreateDate),lastVerified:new Date().toISOString().slice(0,10),status:'unverified',cameraModel:[exif.Make,exif.Model].filter(Boolean).join(' ')};records.push(rec);if(rec.materialLocation)addPhotoMarker(rec);}
 renderRecords();$('recordCount').textContent=records.length;$('importStatus').textContent=`Imported ${files.length} photo${files.length===1?'':'s'}; GPS found in ${gpsCount}. ${files.length-gpsCount} require manual placement.`;if(markers.size){map.fitBounds(L.featureGroup([...markers.values()]).getBounds(),{padding:[30,30],maxZoom:19});}}
function addPhotoMarker(rec){const p=rec.materialLocation;const marker=L.marker([p.latitude,p.longitude],{draggable:true}).addTo(map).bindTooltip(rec.filename);marker.on('dragend',()=>{const q=marker.getLatLng();rec.materialLocation={latitude:q.lat,longitude:q.lng};renderRecords()});markers.set(rec.id,marker)}
function renderRecords(){const el=$('records');el.innerHTML='';if(!records.length){el.innerHTML='<p class="empty-state">Imported photos will appear here.</p>';return;}records.forEach((r,i)=>{const card=document.createElement('article');card.className='record-card';card.innerHTML=`<img src="${r.previewUrl}" alt="Preview of ${esc(r.filename)}"><div><div class="metadata"><strong>${esc(r.filename)}</strong><br>${r.cameraLocation?`GPS: ${r.cameraLocation.latitude.toFixed(6)}, ${r.cameraLocation.longitude.toFixed(6)}`:'GPS not found — click Place on map'}${r.capturedAt?`<br>Captured: ${esc(r.capturedAt)}`:''}${r.cameraModel?`<br>Camera: ${esc(r.cameraModel)}`:''}</div><div class="record-fields"><label>Title<input data-i="${i}" data-k="title" value="${esc(r.title)}" placeholder="Galvanized pipe beside west road"></label><label>Material<input data-i="${i}" data-k="material" value="${esc(r.material)}" placeholder="Steel"></label><label>Geometry / type<input data-i="${i}" data-k="form" value="${esc(r.form)}" placeholder="Square tubing"></label><label>Landmark<input data-i="${i}" data-k="landmark" value="${esc(r.landmark)}" placeholder="Beside red fence"></label><label class="full">Description<textarea data-i="${i}" data-k="description" placeholder="Describe what is visible and what a worker should recognize.">${esc(r.description)}</textarea></label><label class="full">Search tags, comma separated<input data-i="${i}" data-k="tags" value="${esc(r.tags.join(', '))}" placeholder="angle iron, l angle, rusted steel"></label><label class="full">Attributes, comma separated<input data-i="${i}" data-k="attributes" value="${esc(r.attributes.join(', '))}" placeholder="rusted, orange, long, bundled"></label><label class="full">Experienced-worker knowledge<textarea data-i="${i}" data-k="notes" placeholder="What is hidden, nearby, or commonly confused with this material?">${esc(r.notes)}</textarea></label><div class="full button-row"><button type="button" class="secondary-button place-button" data-i="${i}">${r.materialLocation?'Move map to marker':'Place on map center'}</button></div></div></div>`;el.appendChild(card)});el.querySelectorAll('[data-k]').forEach(input=>input.addEventListener('input',updateField));el.querySelectorAll('.place-button').forEach(btn=>btn.addEventListener('click',placeRecord));}
function updateField(e){const r=records[+e.target.dataset.i],k=e.target.dataset.k;r[k]=(k==='tags'||k==='attributes')?e.target.value.split(',').map(v=>v.trim()).filter(Boolean):e.target.value;const m=markers.get(r.id);if(m)m.bindTooltip(r.title||r.filename)}
function placeRecord(e){const r=records[+e.currentTarget.dataset.i];if(r.materialLocation){map.setView([r.materialLocation.latitude,r.materialLocation.longitude],19);markers.get(r.id)?.openTooltip();return;}const c=map.getCenter();r.materialLocation={latitude:c.lat,longitude:c.lng};addPhotoMarker(r);renderRecords();}
function drawBoundary(){if(boundaryLayer)boundaryLayer.remove();if(boundaryPoints.length===1)boundaryLayer=L.circleMarker([boundaryPoints[0].latitude,boundaryPoints[0].longitude],{radius:6,color:'#9b3d22'}).addTo(map);else if(boundaryPoints.length>1)boundaryLayer=L.polygon(boundaryPoints.map(p=>[p.latitude,p.longitude]),{color:'#9b3d22',weight:3,fillOpacity:.08}).addTo(map);}
function exportInventory(){const cleaned=records.map(({previewUrl,...r})=>r);download('inventory.json',JSON.stringify(cleaned,null,2))}
function exportSite(){download('site.json',JSON.stringify({name:'Page Steel',displayName:'Page Steel Material Inventory Map',center,zoom:17,boundary:boundaryPoints,boundaryStatus:boundaryPoints.length>=3?'manually-traced':'awaiting-confirmed-coordinates'},null,2))}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function formatDate(d){if(!d)return'';if(d instanceof Date&&!Number.isNaN(d))return d.toISOString();return String(d)}function esc(v){return(v??'').toString().replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
init();
